### ISSUE TITLE
Ein paar Fragen

### ISSUE THREAD

**Issue by GlitchedAxiom** [ReSpeak/rust-ts3plugin#1]
Moin!

Ich komme aus der Java Welt und meine Erfahrungen mit C Sprachen, Rust und ähnliche beglichen sich auf Null^ Nun muss/will ich ein Teamspeak Plugin programmieren.. Mit der offiziellen Teamspeak SDK habe ich in 2 Stunden nichtmal geschafft Deren Beispiel zu kompilieren.. Mit deiner Lib habe ich es nach 2 Minuten geschafft.. Somit steht schonmal fest das Rust meine nächste Sprache wird die ich angucke, Danke ;)

Die Events habe ich soweit schon verstanden.. Jedoch bleibt mir die Frage wie ich Nachrichten wieder zurückschreiben kann? Ich arbeite mit Privaten Chats.. Somit brauche ich lediglich die Funktion schreiben zu können, und Leute poken zu können. Ich habe gerade nicht wirklich viel dafür gefunden, was mir sagt wie ich das richtig implementiere ;)

Im Hintergrund arbeite ich dann noch mit nem HTTP Server und Client.. Das werde ich aber schon selber implementiert kriegen^ 

Vielen Dank,
Mfg Marcel

PS: Ich denke mal du bist der deutschen Sprache mächtig ;) Das Herkunftsland hat mir das verraten

**Comment by Splamy** [comment]
Hier mal ein kleines Beispiel das dir möglicherweise weiterhelfen könnte.
Die methode schickt eine gegebene `message` über den selben 'Tab' wie sie erhalten wurde zurück.

Für deinen Fall musst du dir nen neue 'ConnectionId' mit der u16 clientId erstellen, mit  `server.get_connection(con)` das entsprechende connection objekt holen und mit `con.send_message(message)` dann senden.

```
fn sendback<S: AsRef<str>>(api: &TsApi, server: &Server, target: MessageReceiver, message: S) {
    if let Err(err) = match target {
        MessageReceiver::Connection(cid) => {
            match server.get_connection(cid) {
                Some(con) => con.send_message(message),
                None => Err(Error::VsCritical),
            }
        }
        MessageReceiver::Channel => {
            let own_id = server.get_own_connection_id();
            match server.get_connection(own_id) {
                Some(own_con) => {
                    match server.get_channel(own_con.get_channel_id()) {
                        Some(chan) => chan.send_message(message),
                        None => Err(Error::VsCritical),
                    }
                }
                None => Err(Error::VsCritical),
            }
        }
        MessageReceiver::Server => server.send_message(message),
    } {
        api.log_or_print(format!("Failed to send: {:?}", err),
                         "tspressor",
                         LogLevel::Info);
    }
}
```

Ps: ich soll ausrichten, dass das Plugin noch nich ganz alle Features realisiert hat. Sollte die also was fehlen mach einfach ein issue auf :wink:
