### ISSUE TITLE
Voice data events

### ISSUE THREAD

**Issue by leMaik** [ReSpeak/rust-ts3plugin#2]
First of all, this wrapper is pretty handy as I want to use Ruby to code a TS3 bot (much more convenient than C).

I'd like to record what a user says when whispering to the bot and previously implemented that in C using the `void ts3plugin_onEditPlaybackVoiceDataEvent(uint64 serverConnectionHandlerID, anyID clientID, short* samples, int sampleCount, int channels)` function.

Unfortunately, this isn't available in rust-ts3plugin and I have no idea how to wrap the samples in Rust. 
Maybe you have one? :)

**Comment by Flakebi** [comment]
Hi,
I'll implement that event soon, it's a bit more complicated than other events because the samples have to be sent to another thread without copying them.

**Comment by Flakebi** [comment]
Editing voice data should work now (implemented in dbea34e).
Let me know if you need more methods that are not yet implemented :).

**Comment by leMaik** [comment]
Thank you very much!

**Comment by Flakebi** [comment]
I found out the TeamSpeak calls the audio callbacks from another thread than the other callbacks which led to crashes in the plugin.
The race conditions are fixed now so it may be worthy to update on the current version (a `cargo update` should be enough).
Also some function signatures changed a bit (now all functions get a mutable reference to the `TsApi` struct).
