### ISSUE TITLE
Current master crashes

### ISSUE THREAD

**Issue by 0xpr03** [ReSpeak/rust-ts3plugin#7]
The commit closing #6 3d6ac43e0c4f44d50ca869b9686024cabce17f0b Crashes teamspeak on a blank plugin with `free(): invalid pointer`.
I'm assuming the new string free-function is not working as intended. Again, a blank plugin, you don't need to call `get_client_property_as_string` at all.

(I was just trying to move production to the current master to add more features, which is why it took so long to appear.)

**Comment by Flakebi** [comment]
Thanks for the heads up, I will try to look into it in the next days.

**Comment by Flakebi** [comment]
Seems like I should not try to free every string from TeamSpeak… For now I removed the free again, at some point I need to look up which strings need to be freed.

For your information, the [v0.3](https://github.com/ReSpeak/rust-ts3plugin/tree/v0.3) branch is now compatible with the sdk version 23 (needed by the 3.3.0 client).
It also has a nicer api compared to 0.2, so you directly get a reference to the server and clients and there is no need to get them all by hand.
Unfortunately it is not yet complete…

**Comment by 0xpr03** [comment]
Hi, thanks for digging into this. I assume you'll have to free strings you request as in get_client_property_as_string, this works on my branch.
I'll try to upgrade to 0.3 and implement all further feaatures on top of it, in the hopes of landing them as PR here. These are mainly connect and disconnect functionality.

**Comment by Flakebi** [comment]
The v0.3 branch has been merged to master
